---
title: "1_Treasure Hunt Task"
output: html_document
date: "2024-03-20"
self_contained: false
---

```{r setup, include=FALSE}

rm(list = ls())
knitr::opts_chunk$set(error = FALSE,echo=FALSE, message=FALSE, warning=FALSE,fig.width = 9,fig.height = 9)

rm(list = ls())
project_dir = rstudioapi::getActiveProject();
src_dir = file.path(project_dir, "src/R", fsep="/")
llr_dir = file.path(project_dir, "src/LLR", fsep="/")

data_dir = file.path(project_dir, "data","Exp2_pilots","4_M2_v3", fsep="/")
result_dir = file.path(project_dir, "results","Exp2_pilots","4_M2_v3", fsep="/")


source(file.path(src_dir,"envSetup.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"funcDef.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"setPlotDefault.R",fsep="/"), local = knitr::knit_global())
#load(file.path(data_dir,"allexpdata_compo_lapse-0_01.RData"))
load(file.path(data_dir,"allexpdata_reclassify.RData"))
data_with_prob = data_with_prob%>%
  filter(islearner=="learner")%>%
  mutate(expt_map = factor(expt_map,levels=c(0,1,2,3),
                           labels=c("training map 1","training map 2",
                                    "cross map 1", "cross map 2")))

max_s1_trial = max(filter(data_with_prob,expt_session==0)$expt_index)
data_with_prob = data_with_prob%>%
  mutate(cross_day_index = ifelse(expt_session==0,expt_index,expt_index+max_s1_trial))%>%
  group_by(subid,expt_session,expt_block,stim_id)%>%
  arrange(expt_index)%>%
  mutate(stim_blockrep = row_number()-1)%>%
  ungroup()%>%
  group_by(subid,expt_session,stim_id)%>%
  arrange(expt_index)%>%
  mutate(stim_sessionrep = row_number()-1)%>%
  ungroup()%>%
  group_by(subid,stim_id)%>%
  arrange(cross_day_index)%>%
  mutate(stim_exptrep = row_number()-1)%>%
  ungroup()

training_rep_idx = data_with_prob%>%
  filter(istraining=="training")%>%
  group_by(subid,expt_session,expt_block)%>%
  mutate(training_exptrep = max(stim_exptrep),
         training_sessionrep = max(stim_sessionrep))%>%
  distinct(subid,expt_session,expt_block,training_exptrep,training_sessionrep)

data_with_prob = left_join(data_with_prob,training_rep_idx,by=c("subid","expt_session","expt_block"))

```

## fit sigmoidal function to behavioural performace

```{r}

stimrepdata_sub = aggregate_data(data_with_prob,
                           yvars = c("resp_dist","LLR_trial","LLRx_trial","LLRy_trial","error_x","error_y","resp_correct"),
                           groupbyvars = c("subid","stim_id","stim_exptrep"),
                           stats = c("mu"),
                           additionalvars = c("islearner","isgeneralizer","iscompositional",
                                              "expt_session","session_str","expt_maptype","expt_map",
                                              "stim_group","iscenter","training_exptrep"))%>%
  change_cols_name(oldnames = c("mu_LLR_trial","mu_LLRx_trial","mu_LLRy_trial",
                                "mu_resp_dist","mu_error_x","mu_error_y","mu_resp_correct"),
                   newnames = c("LLR","LLR_x","LLR_y",
                                "distance","errorx","errory","accuracy"))
```

```{r}
expo_decay = function(params, x) {
  N0 = params[1]
  rate = params[2]
  return(N0*exp(-rate*x))
}

fit_decay = function(fit_x,fit_y){
  model.0 <- lm(log(y) ~ x, data=data.frame(x=fit_x,y=fit_y))
  start <- list(N0=exp(coef(model.0)[1]), rate=-coef(model.0)[2])
  fitmodel <- nls(fit_y~expo_decay(c(N0,rate),fit_x), start = start,
                  control = list(maxiter = 5000))
  params=coef(fitmodel)
  predy = expo_decay(params,fit_x)
  fit_quality = model_quality(expo_decay,params,fit_x,fit_y)
  return(list(param=params,fit_quality=fit_quality,pred_y = predy))
}

model_quality = function(model,params,x,truey){
  predy = model(params,x)
  return(coef(lm(truey~predy))[2])
}


fit_res_dfs = list()
fit_val_dfs = list()
for(currid in unique(stimrepdata_sub$subid)){
  #print(currid)
  subgroup = unique(filter(stimrepdata_sub,subid==currid)$iscompositional)[1]
  tmap1_df = filter(stimrepdata_sub,subid==currid & stim_group=="training" & expt_map == "training map 1")# 336 rows = 16trainingstim*(8*2+4+1)rep/stim
  tmap2_df = filter(stimrepdata_sub,subid==currid & stim_group=="training" & expt_map == "training map 2")
  vmap1_df = filter(stimrepdata_sub,subid==currid & stim_group!="training" & expt_map == "training map 1") # 336 rows = 16trainingstim*(8*2+4+1)rep/stim
  vmap1_df$stim_exptrep = vmap1_df$training_exptrep
  vmap2_df = filter(stimrepdata_sub,subid==currid & stim_group!="training" & expt_map == "training map 2")
  vmap2_df$stim_exptrep = vmap2_df$training_exptrep
  
  stimdfs = list("TrainingMap1-Train" = tmap1_df,
       "TrainingMap2-Train" = tmap2_df,
       "TrainingMap1-Validation" = vmap1_df,
       "TrainingMap2-Validation" = vmap2_df
       )
  for (dfname in names(stimdfs)){
    curr_fit_df = stimdfs[[dfname]]
    # added a small float number to distance so that we can avoid log(0)
    fit_res = fit_decay(curr_fit_df$stim_exptrep,curr_fit_df$distance+1e-20) 
    curr_fit_res_df = data.frame(fit_res$param)
    curr_fit_res_df[["paramname"]] = row.names(curr_fit_res_df)
    row.names(curr_fit_res_df) = NULL
    curr_fit_res_df = curr_fit_res_df%>%  
      mutate(fit_quality= fit_res$fit_quality,
             stimuli    = dfname,
             subid      = currid,
             iscompositional=subgroup 
             )%>%
      change_cols_name("fit_res.param","parameter estimates")
    fit_res_dfs = append(fit_res_dfs,list(curr_fit_res_df))
    
    curr_fit_val_df = data.frame(stim_exptrep=curr_fit_df$stim_exptrep,
                                 pred_distance=fit_res$pred_y,
                                 distance = curr_fit_df$distance)%>%  
      mutate(fit_quality= fit_res$fit_quality,
             stimuli    = dfname,
             subid      = currid,
             iscompositional=subgroup 
             )
    
    fit_val_dfs = append(fit_val_dfs,list(curr_fit_val_df))
  }
  
}
```

```{r,fig.height=3,fig.width=10}
fit_val_df = do.call(rbind,fit_val_dfs)
fit_val_df = separate(fit_val_df,col=stimuli,sep = "-", into = c("maptype", "stimtype"),remove =F)%>%
  mutate(stimtype = paste0(stimtype," stimuli"))
head(fit_val_df)
ggplot(fit_val_df,aes(x=stim_exptrep,color=maptype,group=interaction(subid,stimuli)))+
  facet_nested(cols=vars(stimtype,iscompositional))+
  #geom_line(aes(y=distance),linetype=2)
  geom_line(aes(y=pred_distance))
```


```{r}
fit_res_df = do.call(rbind,fit_res_dfs)%>%
  change_cols_name("parameter estimates","estval")
fit_res_df = separate(fit_res_df,col=stimuli,sep = "-", into = c("maptype", "stimtype"),remove =F)%>%
  mutate(stimtype = paste0(stimtype," stimuli"))
fit_qual_df = fit_res_df%>%
  distinct(subid,stimuli,iscompositional,fit_quality)
fit_qual_df_sum = aggregate_data(fit_qual_df,
                                groupbyvars = c("iscompositional","stimuli"),
                                yvars = "fit_quality",
                                stats=c("mu","se"))
p.modelfit = fit_qual_df%>%
  ggplot(aes(x=stimuli,color=iscompositional))+
  geom_point(aes(y=fit_quality),position=position_dodge(1))+
  geom_col(data=fit_qual_df_sum,aes(y=mu_fit_quality),
           position=position_dodge(1),fill=NA)+
  geom_errorbar(data=fit_qual_df_sum,
                aes(ymin=mu_fit_quality-se_fit_quality,
                    ymax=mu_fit_quality+se_fit_quality),
           position=position_dodge(1),width=0.4)
p.modelfit
```


```{r,fig.height=3,fig.width=10}
fit_res_df_sum = aggregate_data(fit_res_df,
                                groupbyvars = c("iscompositional","stimuli","paramname"),
                                yvars = "estval",
                                additionalvars = c("stimtype","maptype"),
                                stats=c("mu","se"))

ylim_n0 <- range(fit_res_df$estval[fit_res_df$paramname == "N0"])
ylim_rate <- range(fit_res_df$estval[fit_res_df$paramname == "rate"])
fit_res_df%>%
  ggplot(aes(x=iscompositional ,y=estval,color=maptype))+
  facet_nested(~paramname+stimtype,scales="free_y",independent="y")+
  facetted_pos_scales(
    y = list(paramname == "N0" ~ scale_y_continuous(limits = ylim_n0),
             paramname == "rate" ~ scale_y_continuous(limits = ylim_rate,trans="sqrt"))
  )+
  geom_point(position=position_jitterdodge(jitter.width = 0.4,dodge.width = 1))+
  geom_col(data=fit_res_df_sum,aes(y=mu_estval),
           position=position_dodge(1),fill=NA)+
  geom_errorbar(data=fit_res_df_sum,
                aes(y=mu_estval,
                    ymin=mu_estval-se_estval,
                    ymax=mu_estval+se_estval),
                position=position_dodge(1),width=0.4)
```

```{r}
fit_res_df <- within(fit_res_df, maptype <- relevel(factor(fit_res_df$maptype), ref = "TrainingMap1"))
#fit_res_df <- within(fit_res_df, stimtype <- relevel(fit_res_df$stimtype, ref = "Train stimuli"))
fit_res_df <- within(fit_res_df, iscompositional <- relevel(fit_res_df$iscompositional, ref = "non-compositional"))

model_N0tr  = lmer(estval~iscompositional*maptype+ (1|subid),
              data= filter(fit_res_df,paramname == "N0"&stimtype=="Train stimuli")) 
model_N0va  = lmer(estval~iscompositional*maptype+ (1|subid),
              data= filter(fit_res_df,paramname == "N0"&stimtype=="Validation stimuli")) 
model_ratetr= lmer(estval~iscompositional*maptype + (1|subid),
              data= filter(fit_res_df,paramname == "rate"&stimtype=="Train stimuli")) 
model_rateva= lmer(estval~iscompositional*maptype + (1|subid),
              data= filter(fit_res_df,paramname == "rate"&stimtype=="Validation stimuli")) 

export_summs(model_N0tr,model_ratetr,model_N0va,model_rateva,
             error_format = "(\u00B1{std.error})",error_pos ="same",
             model.names=c("N0\nTrain stimuli","decay rate\nTrain stimuli",
                           "N0\nValidation stimuli","decay rate\nValidation stimuli"),
             coefs = c("G>nG" = "iscompositionalcompositional",
                       "Tmap2>Tmap1"  = "maptypeTrainingMap2",
                       "G>nG * Tmap2>Tmap1"  = "iscompositionalcompositional:maptypeTrainingMap2"))
```



## Behavioural performance of learner/generalizer in treasure hunt task{.tabset}
```{r treasurehunt block average}
blockdata_sub = aggregate_data(data_with_prob,
                           yvars = c("resp_dist","LLR_trial","LLRx_trial","LLRy_trial","error_x","error_y","resp_correct","resp_rt"),
                           groupbyvars = c("subid","expt_maptype","expt_map","stim_group","expt_session","blocknumber_withinsess"),
                           stats = c("mu"),
                           additionalvars = c("islearner","isgeneralizer","iscompositional","session_str","expt_maptype"))%>%
  change_cols_name(oldnames = c("mu_LLR_trial","mu_LLRx_trial","mu_LLRy_trial",
                                "mu_resp_dist","mu_error_x","mu_error_y","mu_resp_correct","mu_resp_rt"),
                   newnames = c("LLR","LLR_x","LLR_y",
                                "distance","errorx","errory","accuracy","rt"))


blockdata_sum = aggregate_data(blockdata_sub,
                           yvars = c("distance","LLR","LLR_x","LLR_y","errorx","errory","accuracy","rt"),
                           groupbyvars = c("iscompositional","expt_map","stim_group",
                                           "expt_session","blocknumber_withinsess"),
                           stats = c("mu","se","n"),
                           additionalvars = c("session_str","expt_maptype"))
```


### rescaled distance to goal
```{r}
# with data count

blockdata_sub = left_join(blockdata_sub,change_cols_name(participant_count,"label","generalizer_label"),by=c("iscompositional"))
blockdata_sum = left_join(blockdata_sum,change_cols_name(participant_count,"label","generalizer_label"),by=c("iscompositional"))
```

```{r rescaled distance to goal,fig.height=6}

(p = blockdata_sub%>%
    filter(session_str!="test (no feedback)")%>%
  ggplot(aes(x=blocknumber_withinsess,y=distance,fill=stim_group,color=stim_group))+
  geom_line(aes(group=interaction(stim_group, subid)),
            position=position_dodge(width=0.5),
            alpha = 0.5,linewidth=0.4)+
  geom_point(aes(group=interaction(stim_group, subid)),
             alpha = 0.5,size = 0.8,stroke=0,
             position = position_dodge(width=0.5))+

  geom_line(data = blockdata_sum%>%filter(session_str!="test (no feedback)"),
            aes(x=blocknumber_withinsess,y=mu_distance),
            linewidth=0.8)+
  geom_errorbar(data = blockdata_sum%>%filter(session_str!="test (no feedback)"),
                aes(x=blocknumber_withinsess,
                    y = mu_distance,
                    ymin = mu_distance - se_distance,
                    ymax = mu_distance + se_distance),
                width=0.3)+
    
    
  facet_nested(cols =vars(expt_map,session_str),
               rows = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_x_continuous(breaks = seq(1,36,1))+
  guides(fill = "none")+
  labs(x="block number",y="mean distance to goal (a.u.) rescaled",color = "stim_group",
       title = "Distance to correct location")+
  theme(aspect.ratio = 10,legend.position = "top"))

ggsave(file.path(result_dir,paste0('rescaled_distance_classified','.png')),plot = p,device = 'png',width = 15,height = 8)
```

```{r rt,fig.height=6}

(p = blockdata_sub%>%
    filter(session_str!="test (no feedback)")%>%
  ggplot(aes(x=blocknumber_withinsess,y=rt,fill=stim_group,color=stim_group))+
  geom_line(aes(group=interaction(stim_group, subid)),
            position=position_dodge(width=0.5),
            alpha = 0.5,linewidth=0.4)+
  geom_point(aes(group=interaction(stim_group, subid)),
             alpha = 0.5,size = 0.8,stroke=0,
             position = position_dodge(width=0.5))+

  geom_line(data = blockdata_sum%>%filter(session_str!="test (no feedback)"),
            aes(x=blocknumber_withinsess,y=mu_rt),
            linewidth=0.8)+
  geom_errorbar(data = blockdata_sum%>%filter(session_str!="test (no feedback)"),
                aes(x=blocknumber_withinsess,
                    y = mu_rt,
                    ymin = mu_rt - se_rt,
                    ymax = mu_rt + se_rt),
                width=0.3)+
    
    
  facet_nested(cols =vars(expt_map,session_str),
               rows = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_x_continuous(breaks = seq(1,36,1))+
  guides(fill = "none")+
  labs(x="block number",y="RT",color = "stim_group",
       title = "RT")+
  theme(aspect.ratio = 10,legend.position = "top"))

ggsave(file.path(result_dir,paste0('rt_classified','.png')),plot = p,device = 'png',width = 15,height = 8)
```

```{r,fig.height=4}
testnofbdata = filter(data_with_prob,session_str=="test (no feedback)")%>%
  mutate(
    stim_type = ifelse(stim_x*stim_y==0,"center","non center")
  )
testnofbdata_sub = aggregate_data(testnofbdata,
                           yvars = c("resp_dist","LLR_trial","LLRx_trial","LLRy_trial","error_x","error_y","resp_correct","resp_rt"),
                           groupbyvars = c("subid","expt_maptype","stim_type","expt_session"),
                           stats = c("mu"),
                           additionalvars = c("iscompositional","session_str","expt_maptype"))%>%
  change_cols_name(oldnames = c("mu_LLR_trial","mu_LLRx_trial","mu_LLRy_trial",
                                "mu_resp_dist","mu_error_x","mu_error_y","mu_resp_correct",
                                "mu_resp_rt"),
                   newnames = c("LLR","LLR_x","LLR_y",
                                "distance","errorx","errory","accuracy","rt"))


testnofbdata_sum = aggregate_data(testnofbdata_sub,
                           yvars = c("distance","LLR","LLR_x","LLR_y","errorx","errory","accuracy","rt"),
                           groupbyvars = c("iscompositional","expt_maptype","stim_type",
                                           "expt_session"),
                           stats = c("mu","se","n"),
                           additionalvars = c("session_str","expt_maptype"))


testnofbdata_sub = left_join(testnofbdata_sub,change_cols_name(participant_count,"label","generalizer_label"),by=c("iscompositional"))
testnofbdata_sum = left_join(testnofbdata_sum,change_cols_name(participant_count,"label","generalizer_label"),by=c("iscompositional"))

(p = testnofbdata_sub%>%
  ggplot(aes(x=stim_type,y=distance,color=expt_maptype))+
  geom_point(alpha = 0.3,size = 2,stroke=0,position=position_dodge(1))+
  geom_col(data = testnofbdata_sum,
            aes(x=stim_type,y=mu_distance),fill=NA,
           position=position_dodge(1))+
  geom_errorbar(data = testnofbdata_sum,
                aes(x=stim_type,
                    y = mu_distance,
                    ymin = mu_distance - se_distance,
                    ymax = mu_distance + se_distance),
                width=0.4,
                position=position_dodge(1))+
  facet_nested(cols = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_color_manual(values=twolevel_colors)+
  guides(fill = "none")+
  labs(x="stim_type",y="mean distance to goal (a.u.) rescaled",color = "map type",
       title = "Distance to correct location")+
  theme(aspect.ratio = 4,legend.position = "top"))



```

```{r,fig.height=4}
(p = testnofbdata_sub%>%
  ggplot(aes(x=stim_type,y=distance,color=expt_maptype))+
  geom_point(alpha = 0.3,size = 2,stroke=0,position=position_dodge(1))+
  geom_col(data = testnofbdata_sum,
            aes(x=stim_type,y=mu_distance),fill=NA,
           position=position_dodge(1))+
  geom_errorbar(data = testnofbdata_sum,
                aes(x=stim_type,
                    y = mu_distance,
                    ymin = mu_distance - se_distance,
                    ymax = mu_distance + se_distance),
                width=0.4,
                position=position_dodge(1))+
  facet_nested(cols = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_color_manual(values=twolevel_colors)+
  guides(fill = "none")+
  labs(x="stim_type",y="mean distance to goal (a.u.) rescaled",color = "map type",
       title = "Distance to correct location")+
  theme(aspect.ratio = 4,legend.position = "top"))
```




```{r,fig.height=4}
(p = testnofbdata_sub%>%
  ggplot(aes(x=stim_type,y=rt,color=expt_maptype))+
  geom_point(alpha = 0.3,size = 2,stroke=0,position=position_dodge(1))+
  geom_col(data = testnofbdata_sum,
            aes(x=stim_type,y=mu_rt),fill=NA,
           position=position_dodge(1))+
  geom_errorbar(data = testnofbdata_sum,
                aes(x=stim_type,
                    y = mu_rt,
                    ymin = mu_rt - se_rt,
                    ymax = mu_rt + se_rt),
                width=0.4,
                position=position_dodge(1))+
  #geom_line(aes(group=interaction(subid)),
  #           alpha = 0.2,size = 0.5,color="black")+
  facet_nested(cols = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
   scale_color_manual(values=twolevel_colors)+
  guides(fill = "none")+
  labs(x="stim_type",y="RT",color = "map type",
       title = "Treasure Hunt RT")+
  theme(aspect.ratio = 4,legend.position = "top"))
```
```{r}
model_rt_trial_g   = lmer(resp_rt~iscenter+expt_maptype + (iscenter|subid) + (1|stim_id),
              data=filter(testnofbdata,iscompositional=="compositional"&resp_correct==TRUE))
model_error_trial_g   = glmer(resp_correct~iscenter+expt_maptype + (iscenter|subid) + (1|stim_id),
              data=filter(testnofbdata,iscompositional=="compositional"))
#model_dist = lmer(distractor_dist~iscompositional+blocknumber_withinsess + (1 |subid),
#              data=fc_df)
export_summs(model_rt_trial_g,model_error_trial_g,error_format = "(\u00B1{std.error})",error_pos ="same",
             model.names=c("RT in Generalizers","Error in Generalizers"),
             coefs = c("Center>nonCenter" = "iscentercenter",
                       "Cmap>Tmap"  = "expt_maptypecross maps"
                       ))
```


```{r, fig.height=4,fig.width=3}
testnofbdata = filter(data_with_prob,session_str=="test (no feedback)")%>%
  mutate(
    stim_type = ifelse(stim_x*stim_y==0,"center","non center")
  )
testnofbdata_sub = aggregate_data(testnofbdata,
                           yvars = c("resp_dist","LLR_trial","LLRx_trial","LLRy_trial","error_x","error_y","resp_correct","resp_rt"),
                           groupbyvars = c("subid","iscenter"),
                           stats = c("mu"),
                           additionalvars = c("iscompositional"))%>%
  change_cols_name(oldnames = c("mu_LLR_trial","mu_LLRx_trial","mu_LLRy_trial",
                                "mu_resp_dist","mu_error_x","mu_error_y","mu_resp_correct",
                                "mu_resp_rt"),
                   newnames = c("LLR","LLR_x","LLR_y",
                                "distance","errorx","errory","accuracy","rt"))


testnofbdata_sum = aggregate_data(testnofbdata_sub,
                           yvars = c("distance","LLR","LLR_x","LLR_y","errorx","errory","accuracy","rt"),
                           groupbyvars = c("iscompositional","iscenter"),
                           stats = c("mu","se","n"))


testnofbdata_sub = left_join(testnofbdata_sub,change_cols_name(participant_count,"label","generalizer_label"),by=c("iscompositional"))
testnofbdata_sum = left_join(testnofbdata_sum,change_cols_name(participant_count,"label","generalizer_label"),by=c("iscompositional"))

(p = testnofbdata_sub%>%
  ggplot(aes(x=iscenter,y=distance,color=iscenter))+
  geom_point(alpha = 0.3,size = 2,stroke=0)+
  geom_col(data = testnofbdata_sum,
            aes(x=iscenter,y=mu_distance),fill=NA)+
  geom_errorbar(data = testnofbdata_sum,
                aes(x=iscenter,
                    y = mu_distance,
                    ymin = mu_distance - se_distance,
                    ymax = mu_distance + se_distance),
                width=0.4)+
  facet_nested(cols = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_color_manual(values=twolevel_colors)+
  guides(fill = "none")+
  labs(x="stimuli type",y="mean distance to goal (a.u.) rescaled",color = "stimuli type",
       title = "Treasure Hunt \n Error")+
  theme(aspect.ratio = 5,legend.position = "top"))

(p = testnofbdata_sub%>%
  ggplot(aes(x=iscenter,y=rt,color=iscenter))+
  geom_point(alpha = 0.3,size = 2,stroke=0)+
  geom_col(data = testnofbdata_sum,
            aes(x=iscenter,y=mu_rt),fill=NA)+
  geom_errorbar(data = testnofbdata_sum,
                aes(x=iscenter,
                    y = mu_rt,
                    ymin = mu_rt - se_rt,
                    ymax = mu_rt + se_rt),
                width=0.4)+
  facet_nested(cols = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_color_manual(values=twolevel_colors)+
  guides(fill = "none")+
  labs(x="stimuli type",y="mean distance to goal (a.u.) rescaled",color = "stimuli type",
       title = "Treasure Hunt \n RTs")+
  theme(aspect.ratio = 5,legend.position = "top"))

```


### mean LLR
```{r,fig.height=6}
#withdatacount
(p = blockdata_sub%>%
    filter(session_str!="test (no feedback)")%>%
  ggplot(aes(x=blocknumber_withinsess,y=LLR,fill=stim_group,color=stim_group))+
  geom_point(alpha = 0.3,size = 2,stroke=0)+
  geom_line(data = blockdata_sum%>%filter(session_str!="test (no feedback)"),
            aes(x=blocknumber_withinsess,y=mu_LLR))+
  geom_errorbar(data = blockdata_sum%>%filter(session_str!="test (no feedback)"),
                aes(x=blocknumber_withinsess,
                    y = mu_LLR,
                    ymin = mu_LLR - se_LLR,
                    ymax = mu_LLR + se_LLR),
                width=0.4)+
  facet_nested(cols =vars(expt_map,session_str),
               rows = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
  scale_x_continuous(breaks = seq(1,36,1))+
  guides(fill = "none")+
  labs(x="block number",y="mean LLR",color = "stim_group",
       title = "Log-Likelihood Ratio")+
  theme(aspect.ratio = 11,legend.position = "top"))



ggsave(file.path(result_dir,paste0('LLR_classified','.png')),plot = p,device = 'png',width = 15,height = 8)
```

```{r,fig.height=4}
(p = testnofbdata_sub%>%
  ggplot(aes(x=stim_type,y=LLR,color=expt_maptype))+
  geom_point(alpha = 0.3,size = 2,stroke=0,position=position_dodge(1))+
  geom_col(data = testnofbdata_sum,
            aes(x=stim_type,y=mu_LLR),fill=NA,
           position=position_dodge(1))+
  geom_errorbar(data = testnofbdata_sum,
                aes(x=stim_type,
                    y = mu_LLR,
                    ymin = mu_LLR - se_LLR,
                    ymax = mu_LLR + se_LLR),
                width=0.4,
                position=position_dodge(1))+
  facet_nested(cols = vars(generalizer_label),
               scales = "free_x",space = "free_x")+
   scale_color_manual(values=twolevel_colors)+
  guides(fill = "none")+
  labs(x="stim_type",y="mean LLR",color = "map type",
       title = "meanLLR")+
  theme(aspect.ratio = 4,legend.position = "top"))
```


### Individual response map
```{r 2D + 1D LLR}
for (pid in unique(filter(data_with_prob)$subid)){
  map_name_list = c("training map1\n(x1y1)","training map2\n(x2y2)",
                    "cross map1\n(x1y2)","cross map2\n(x2y1)")
  current_data = filter(data_with_prob,subid == pid)%>%
    mutate(stim_attrx = factor(stim_attrx),
           stim_attry = factor(stim_attry),
           expt_mapname= case_when(expt_map=="training map 1"~map_name_list[1],
                                   expt_map=="training map 2"~map_name_list[2],
                                   expt_map=="cross map 1"~map_name_list[3],
                                   expt_map=="cross map 2"~map_name_list[4]
                                   ),
           block_name = paste(session_str,blocknumber_withinsess," "))%>%
    mutate(h1 = factor(ifelse(expt_session==0,expt_mapname,block_name),
                       levels = c(map_name_list[1:2],
                                  paste("refresher",seq(1,4,1)," "),
                                  paste("test (no feedback)",seq(1,1,1)," "))),
           h2 = factor(ifelse(expt_session==0,block_name,expt_mapname)))
  
  current_data_sum = current_data%>%
    aggregate_data(groupbyvars = c("h1","h2"),
                   yvars=c("LLRx_trial","LLRy_trial","LLR_trial"),
                   stats = "mu")%>%
    change_cols_name(oldnames = c("mu_LLRx_trial","mu_LLRy_trial","mu_LLR_trial"),
                     newnames = c("LLR_x","LLR_y","LLR"))
  
  plot_name = paste(pid,unique(current_data$iscompositional))
  (p = current_data%>%
    ggplot(aes(x=resp_x, y = resp_y))+
    facet_nested_wrap(vars(h1,h2),ncol = 8)+
    geom_point(aes(shape = stim_attry, color = stim_attrx,fill = stim_attrx),size=3.5,alpha=0.7)+
    geom_text(data = current_data_sum,size = 3,
            aes(x=0.1,y=2,label = sprintf("2D LLR = %s", formatC(LLR, digits = 2))))+
    geom_text(data = current_data_sum,size = 3,
              aes(x=0.1,y=1.6,
                  label = sprintf("1D LLR(x,y): [%s, %s]",
                                  formatC(LLR_x, digits = 2),
                                  formatC(LLR_y, digits = 2))))+
    scale_color_manual(values = y_colors,aesthetics = c("color","fill"))+
    #scale_shape_manual(values = x_shapes)+
    guides(fill = "none")+
    labs(title = plot_name,
         color = "x feature",shape = "y feature", x = "x", y = "y")+
    theme(legend.position = "top"))
  show(p)
  ggsave(file.path(result_dir,'individualmaps',"participant_map_with1dLLR",paste0(pid,'.png')),plot = p,width = 16,height = 13)
  
}
```

### average response map
```{r}
generalize_js = c("compositional","non-compositional")
for (j in generalize_js){
    map_name_list = c("training map1\n(x1y1)","training map2\n(x2y2)",
                    "cross map1\n(x1y2)","cross map2\n(x2y1)")
    ave_resp_map_df = data_with_prob %>%
    filter(iscompositional==j)%>%
    mutate(stim_attrx = factor(stim_attrx),
           stim_attry = factor(stim_attry),
           expt_mapname= case_when(expt_map=="training map 1"~map_name_list[1],
                                   expt_map=="training map 2"~map_name_list[2],
                                   expt_map=="cross map 1"~map_name_list[3],
                                   expt_map=="cross map 2"~map_name_list[4]
                                   ),
           block_name = paste(session_str,blocknumber_withinsess," "))%>%
    mutate(h1 = factor(ifelse(expt_session==0,expt_mapname,block_name),
                       levels = c(map_name_list[1:2],
                                  paste("refresher",seq(1,4,1)," "),
                                  paste("test (no feedback)",seq(1,1,1)," "))),
           h2 = factor(ifelse(expt_session==0,block_name,expt_mapname)))
  
    if (nrow(ave_resp_map_df)>0){
        p = 
        ave_resp_map_df%>%
          mutate(block_name = paste(session_str,blocknumber_withinsess))%>%
        ggplot(aes(x=resp_x, y = resp_y))+
        facet_nested_wrap(vars(h1,h2),ncol = 8)+
        geom_point(aes(color = stim_attry,fill = stim_attry,shape = stim_attrx),size = 1)+
        scale_color_manual(values = y_colors,aesthetics = c("color","fill"))+
        scale_shape_manual(values = x_shapes)+
        guides(fill = "none")+
        labs(title =paste0("average response map: ",j),
             color = "y feature",shape = "x feature", x = "x", y = "y")+
        theme(legend.position = "top")
      ggsave(file.path(result_dir,'individualmaps',"averagemaps",
                       paste0(j,'.png')),plot = p,width = 12,height = 10)
      show(p)
    }

}

```



# compositional strategy
```{r}
strategy_df = read.csv(file.path(data_dir,"compo_strategy.csv"))%>%
  mutate(xyratio = beta_putativex/(beta_putativex+beta_putativey),
         logxy   = log(beta_putativex/beta_putativey))%>%
  mutate(iscompositional = factor(ifelse(subid %in% compositional_ids,"compositional","non-compositional"),
                                  levels=c("compositional","non-compositional")),
         expt_session    = ifelse(expt_block>=8*2+4,2,expt_session))%>%
  group_by(subid,expt_map)%>%
  arrange(expt_session,expt_block)%>%
  mutate(block_withinmapsess = row_number())%>%
  ungroup()%>%
  mutate(session_str=factor(expt_session,levels=c(0,1,2),labels=c("pre-train","refresher","test (no feedback)")),
         expt_map     = factor(expt_map,levels=c(0,1,2,3)),
         expt_maptype = factor(if_else(expt_map%in%c(0,1),"training maps","cross maps"),levels=c("training maps","cross maps")))

```


```{r}
S_sqrt <- function(x){sign(x)*sqrt(abs(x))}
IS_sqrt <- function(x){x^2*sign(x)}
S_sqrt_trans <- function() scales::trans_new("S_sqrt",S_sqrt,IS_sqrt)

strategy_df%>%
  mutate(expt_mapname= factor(expt_map,levels=c(0,1,2,3),
                              labels=c("training map1\n(x1y1)","training map2\n(x2y2)",
                                       "cross map1\n(x1y2)","cross map2\n(x2y1)")))%>%
ggplot()+
  geom_point(aes(x=beta_putativex,y=beta_putativey,color=iscompositional))+
  facet_nested_wrap(vars(session_str,expt_mapname,block_withinmapsess),ncol = 8)+
  scale_y_continuous(trans="S_sqrt")+
  scale_x_continuous(trans="S_sqrt")+
  geom_abline(slope=1)
```

