---
title: "RTanalysis"
author: "zilu"
date: "2024-12-05"
output: html_document
---
```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(error = FALSE,echo=FALSE, message=FALSE, warning=FALSE)

rm(list = ls())
project_dir = rstudioapi::getActiveProject();
src_dir = file.path(project_dir, "src/R", fsep="/")
llr_dir = file.path(project_dir, "src/LLR", fsep="/")

data_dir = file.path(project_dir, "data","Exp1_fmri", fsep="/")
result_dir = file.path(project_dir, "results","Exp1_fmri", fsep="/")


source(file.path(src_dir,"envSetup.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"funcDef.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"setPlotDefault.R",fsep="/"), local = knitr::knit_global())
```

```{r}
data_with_prob = loadRData(file.path(data_dir,"filtereddata_withprob_compo_lapse-0_01.RData"))
meanscanperf_with_prob = loadRData(file.path(data_dir,"filteredmeanscannerdata_withprob_compo_lapse-0_01.RData"))

```

## effect of counting on RT
```{r}
interquatile_r = IQR(log(filter(data_with_prob,expt_session==3&stage=="test")$resp_rt),na.rm=T)
q25 = quantile(log(filter(data_with_prob,expt_session==3&stage=="test")$resp_rt),0.25,na.rm=T)
data_with_prob = data_with_prob%>%
  mutate(resp_rt_rep18 = if_else(resp_rt<0.8,NA,resp_rt))%>% #exclude trials that are too fast
  mutate(resp_rt_ms = resp_rt*1000)%>%
  mutate(startdist = scale(sqrt((start_x-stim_x)**2 + (start_y-stim_y)**2)),
         moveddist = scale(sqrt((start_x-resp_x)**2 + (start_y-resp_y)**2)),
         x_order = as.integer(stim_x*2+3),
         y_order = as.integer(stim_y*2+3),
         resp_rtint = (resp_rt_ms+1000),
         logrt = log(resp_rt_ms),
         logrtint = log(resp_rtint))%>%
  mutate(counting = x_order+y_order)

if(!require(corrr)){
    install.packages("corrr")
}

library(corrr)
rt_corr_quickcheckdf = do.call(
  rbind,
  lapply(filter(data_with_prob, isgeneralizer=="generalizer"&expt_session==3&cohort=="second cohort") %>% 
    group_split(subid),
    function(d){d%>%correlate() %>%focus(resp_rt_ms,moveddist)})
  )%>%
  group_by(term)%>%
  summarise(resp_rt_ms = mean(resp_rt_ms),
            moveddist  = mean(moveddist))
```

```{r}
hasConverged <- function (mm) {
  
  if ( !inherits(mm, "merMod")) stop("Error: must pass a lmerMod object")
  
  retval = NULL
  
  if(is.null(unlist(mm@optinfo$conv$lme4))) {
    retval = 1
  }
  else {
    if (isSingular(mm)) {
      retval = 0
    } else {
      retval = -1
    }
  }
  return(retval)
}
```




```{r}
#c1 = lmer(data = filter(data_with_prob,stage=="test"&expt_session==3&cohort=="first cohort"),
#     "resp_rtint~isgeneralizer*counting+moveddist+LR_trial+(LLR_trial|subid)+(counting|subid)+(moveddis#t|subid)+(1|subid)")

rt_countingformula = "resp_rt_ms~expt_trial+LR_trial+x_order+y_order+moveddist+(1|run:subid)+(1|subid)" # didnt add random slope bc lead to singular fit

Gc1 = lmer(data = filter(data_with_prob,isgeneralizer=="generalizer"&stage=="test"&expt_session==3&cohort=="first cohort"),rt_countingformula)

Gc2 = lmer(data = filter(data_with_prob,isgeneralizer=="generalizer"&stage=="test"&expt_session==3&cohort=="second cohort"),rt_countingformula)

NGc1= lmer(data = filter(data_with_prob,isgeneralizer=="non-generalizer"&stage=="test"&expt_session==3&cohort=="first cohort"),rt_countingformula)

NGc2= lmer(data = filter(data_with_prob,isgeneralizer=="non-generalizer"&stage=="test"&expt_session==3&cohort=="second cohort"),rt_countingformula)

hasConverged(Gc1)
hasConverged(Gc2)
hasConverged(NGc1)
hasConverged(NGc2)
export_summs(Gc1,Gc2,NGc1,NGc2,
             model.names = c("Generalizer\nFirst Cohort","Generalizer\nSecond Cohort",
                             "Non-Generalizer\nFirst Cohort","Non-Generalizer\nSecond Cohort"))
```

```{r}
rt_nocountingformula = "resp_rt_ms~expt_trial+LR_trial+moveddist+(1|run:subid)+(1|subid)"

bGc1 = lmer(data = filter(data_with_prob,isgeneralizer=="generalizer"&stage=="test"&expt_session==3&cohort=="first cohort"),rt_nocountingformula)

bGc2 = lmer(data = filter(data_with_prob,isgeneralizer=="generalizer"&stage=="test"&expt_session==3&cohort=="second cohort"),rt_nocountingformula)

bNGc1= lmer(data = filter(data_with_prob,isgeneralizer=="non-generalizer"&stage=="test"&expt_session==3&cohort=="first cohort"),rt_nocountingformula)

bNGc2= lmer(data = filter(data_with_prob,isgeneralizer=="non-generalizer"&stage=="test"&expt_session==3&cohort=="second cohort"),rt_nocountingformula)

mc_tabnames = c("\n\nGeneralizer\nFirst Cohort","\n\nGeneralizer\nSecond Cohort",
                "\n\nNon-Generalizer\nFirst Cohort","\n\nNon-Generalizer\nSecond Cohort")
mc_dfs  = list(anova(bGc1,Gc1), anova(bGc2,Gc2),
            anova(bNGc1,NGc1), anova(bNGc2,NGc2))
for (j in seq(1,4)){
  writeLines(mc_tabnames[j])
  print(md_table(mc_dfs[[j]],format="simple",row.names=c("without counting","with counting")))
  
}
print(sjPlot::tab_df(anova(bGc1,Gc1),title="Generalizer\nFirst Cohort"),use.viewer=F)
print(sjPlot::tab_df(anova(bGc2, Gc2),title="Generalizer\nSecond Cohort"),use.viewer=F)
print(sjPlot::tab_df(anova(bNGc1, NGc1),title="Non-Generalizer\nFirst Cohort"),use.viewer=F)
print(sjPlot::tab_df(anova(bNGc2, NGc2),title="Non-Generalizer\nSecond Cohort"),use.viewer=F)

```


```{r}

rt_countingformula = "resp_rt_ms~expt_trial+LR_trial+x_order+y_order+moveddist+(1|subid:run)+(-1+y_order|subid)+(-1+x_order|subid)+(1|subid)" # didnt add random slope bc lead to singular fit
#isgeneralizer=="generalizer"
G_C1C2 = lmer(data = filter(data_with_prob,isgeneralizer=="generalizer"&stage=="test"&expt_session==3),rt_countingformula)

hasConverged((G_C1C2))

ranef(G_C1C2)$subid
```


```{r}


cal_unexpvar = function(d,rtvar){
  f = paste0(rtvar,"~moveddist+expt_trial+LR_trial")
  m = lm(f,data=d)
  uev = 1-summary(m)[["r.squared"]]
  
  return(list(resid=m[["residuals"]],uev=uev))
}

cal_counting_coef = function(d,rtvar){
  f2 = paste0(rtvar,"~moveddist+expt_trial+LR_trial+x_order+y_order")
  m2 = lm(f2,data=d)
  m2_coef_sum = summary(m2)[["coefficients"]]
  df = data.frame(m2_coef_sum)%>%
    change_cols_name(c("Estimate","Std..Error","t.value","Pr...t.."),c("est","std","t","p"))
  df[["IV"]] = unlist(lapply(row.names(df),function(x){str_remove_all(x,"[()]")}))
  m2_coef_sum = df%>%pivot_longer(cols=c("est","std","t","p"),names_to="stat")
  return(m2_coef_sum)
}

rtresid_dfs = lapply(
  group_split(filter(data_with_prob,expt_session==3&stage=="test"),cohort,islearner,isgeneralizer,subid,stage), 
  function(d){
        d = d%>%dplyr::select(-c("Unnamed..0","X"))%>%filter(!is.na(resp_rt_ms))
        if(nrow(d)>1){
          resid_op = cal_unexpvar(d,"resp_rt_ms")
          d[["rt_resid"]] = resid_op[["resid"]]
        } 
      return(d)  
      }
)
rt_afterdist_resid_df = do.call(rbind,rtresid_dfs)

substageblock_data_splits = group_split(filter(data_with_prob,!is.na(cycle)&stage=="test"),
                                        subid,cycle,stage)
rtcoef_dfs = lapply(
  substageblock_data_splits, 
  function(d){
        d = d%>%dplyr::select(-c("Unnamed..0","X"))%>%filter(!is.na(resp_rt_ms))
        if(nrow(d)>1){
          coef_sum = cal_counting_coef(d,"resp_rt_ms")
          iddf = d%>%distinct(cohort,islearner,isgeneralizer,subid,stage,cycle)
          coef_sum = cbind(iddf[rep(1, each = nrow(coef_sum)), ],coef_sum)
          return(coef_sum)  
        } 
      }
)        
rt_coef_df = do.call(rbind,rtcoef_dfs)

```


```{r,fig.width=6}
rt_counting_coef_sub_cycle = rt_coef_df%>%
  filter(IV%in%c("x_order","y_order")&stat=="est")%>%
  mutate(IV = factor(IV,levels=c("x_order","y_order"),labels=c("x","y")))%>%
  pivot_wider(id_cols = c("cohort","islearner","isgeneralizer","subid","stage","cycle"),
              values_from = "value", names_from ="IV")%>%
  mutate(tamapping = if_else(sign(x)==sign(y),1,-1))%>%
  mutate(tamapping_weight = tamapping*0.5*((abs(x)+abs(y))))         

rt_counting_coef_sub_cycle_wide = rt_counting_coef_sub_cycle%>%
  pivot_wider(id_cols = c("cohort","islearner","isgeneralizer","subid","stage"),
              values_from = "tamapping", names_from ="cycle",names_prefix = "tamapping_")

rt_counting_coef_sub_cycle_wide%>%
  mutate(lstr=if_else(sign(tamapping_3)!=sign(tamapping_4),subid,""),
         jitterx = tamapping_3+runif(nrow(rt_counting_coef_sub_cycle_wide),-0.3,0.3),
         jittery = tamapping_4+runif(nrow(rt_counting_coef_sub_cycle_wide),-0.3,0.3))%>%
ggplot(aes(y=jitterx,x=jittery,color=cohort))+
  facet_wrap2(vars(isgeneralizer),nrow=2,axes="all")+
  #geom_jitter(width=0.4,height=0.4,alpha=0.8)+
  geom_point(alpha=0.8)+
  geom_hline(yintercept=0,linetype ="dashed")+
  geom_vline(xintercept=0,linetype ="dashed")+
  labs(y="scanning", x = "pretraining")+
  scale_x_continuous(breaks=c(1,-1),labels=c("top-left","top-right"),limits = c(-1.5,1.5))+
  scale_y_continuous(breaks=c(1,-1),labels=c("top-left","top-right"),limits = c(-1.5,1.5))+
  theme(panel.border=element_rect(fill = NA),
        legend.position = "top")+
  geom_text(x=-0.8,y=0.31,label="inconsistent",color="darkgrey")+
  geom_text(x=0.8,y=-0.31,label="inconsistent",color="darkgrey")+
  geom_text(x=0.8,y=0.31,label="top-left",color="darkgrey")+
  geom_text(x=-0.8,y=-0.31,label="top-right",color="darkgrey")#+
#  geom_text(aes(label=lstr),size=2)


training_axis_mapping = rt_counting_coef_sub_cycle_wide%>%
  filter(stage=="test")%>%
  mutate(tamapping = case_when(
    tamapping_4==tamapping_3~tamapping_4, #(countx_p<0.05)&(county_p<0.05) 
    tamapping_4!=tamapping_3~0)
    )%>%
  mutate(tamapping_str = factor(tamapping,levels=c(1,-1,0),labels=c("topleft","topright","inconsistent")))
ggplot(training_axis_mapping,
       aes(x=tamapping_str,color=cohort))+
  facet_grid(cols=vars(isgeneralizer))+
  geom_bar(position=position_dodge(),fill=NA)


```


```{r}
rt_counting_coef_sub = rt_coef_df%>%
  filter(IV%in%c("x_order","y_order")&stage=="test"&cycle==4)%>%
  dplyr::select(-c("stage","cycle"))%>%
  pivot_wider(id_cols = c("cohort","IV","islearner","isgeneralizer","subid"),
              values_from = "value", names_from ="stat")%>%
  change_cols_name("est","regcoef")

rt_counting_coef_sum = rt_counting_coef_sub%>%
  aggregate_data(groupbyvars = c("cohort","islearner","isgeneralizer","IV"),
                 yvars = "regcoef",
                 stats=c("mu"))

rt_counting_coef_sub_wide = rt_counting_coef_sub%>%
  pivot_wider(id_cols = c("cohort","islearner","isgeneralizer","subid"),
              values_from = "regcoef",
              names_from ="IV")
ggplot(rt_counting_coef_sub_wide,aes(x=x_order  ,y=y_order  ,color=cohort))+
  facet_grid(cols=vars(isgeneralizer))+
  geom_point()+
  geom_hline(yintercept=0,linetype="dashed")+
  geom_vline(xintercept=0,linetype="dashed")+
  labs(x="Beta_stimx",y="Beta_stimy")+
  theme(legend.position="top")

rt_counting_coefwithp_sub = rt_counting_coef_sub%>%
  pivot_wider(id_cols=c("cohort","islearner","isgeneralizer","subid"),
              values_from = c("regcoef","p"),
              names_from = "IV")%>%
  change_cols_name(c("regcoef_x_order","regcoef_y_order","p_x_order","p_y_order"),
                   c("countx_coef","county_coef","countx_p","county_p"))

#nrow(rt_coef_df_wide) == length(unique(scanning_beh$subid))
#nrow(rt_counting_coefwithp_sub) == length(unique(scanning_beh$subid))

training_axis_mapping = rt_counting_coefwithp_sub%>%
  mutate(tamapping = case_when(
    sign(countx_coef)==sign(county_coef)~1, #(countx_p<0.05)&(county_p<0.05) 
    sign(countx_coef)!=sign(county_coef)~-1, # abs(countx_coef)>11.57369&abs(county_coef)>10.10267&
    .default = 0)
    )%>%
  mutate(tamapping_str = factor(tamapping,levels=c(1,-1,0),labels=c("topleft","topright","orthogonal")),
       ave_abs_count_coef = (abs(countx_coef)+abs(countx_coef))/2)%>%
  dplyr::select(c("cohort","islearner","isgeneralizer","subid","tamapping","tamapping_str",
                  "countx_coef","county_coef","ave_abs_count_coef","countx_p","county_p"))

ggplot(training_axis_mapping,aes(x=tamapping_str,color=isgeneralizer))+geom_bar(position=position_dodge(),fill=NA)
```





```{r}
rt_counting_coef_sub_long = rt_counting_coef_sub%>%
  mutate(countaxis = factor(IV,levels=c("x_order","y_order"),labels=c("count x","count y")),
         absregcoef = abs(regcoef))

rt_counting_coef_sum_long = rt_counting_coef_sub_long%>%
  aggregate_data(groupbyvars=c("cohort","isgeneralizer", "countaxis"),
                 yvars=c("regcoef","absregcoef"),
                 stats=c("mu","se"))

ggplot(data=rt_counting_coef_sub_long,
       aes(x=isgeneralizer,color=countaxis))+
  facet_nested(cols=vars(cohort),
               scale="free_x")+
  geom_point(aes(y=regcoef),
             alpha=0.5,
             position=position_jitterdodge(jitter.width=0.2,dodge.width = 0.9)
             #position=position_dodge(width=0.9)
           )+
  geom_col(data = rt_counting_coef_sum_long,
           aes(y=mu_regcoef),
           #method = "lm",se=F,na.rm = T,formula='y ~ x',
           position=position_dodge(width=0.9),
           fill=NA)+
  geom_point(data = rt_counting_coef_sum_long, 
           aes(y=mu_regcoef),
           position=position_dodge(width=0.9)
           )+
  geom_errorbar(data = rt_counting_coef_sum_long, 
           aes(ymin=mu_regcoef-se_regcoef,
               ymax=mu_regcoef+se_regcoef),
           position=position_dodge(width=0.9),
           width=0.4)+
  labs(y="regression coefficient of counting")+
  theme(legend.position = "top",legend.direction = "horizontal",
        aspect.ratio = 1)

ggplot(data=rt_counting_coef_sub_long,
       aes(x=isgeneralizer,color=countaxis))+
  facet_nested(cols=vars(cohort),
               scale="free_x")+
  geom_point(aes(y=absregcoef),
             alpha=0.5,
             position=position_jitterdodge(jitter.width=0.2,dodge.width = 0.9)
             #position=position_dodge(width=0.9)
           )+
  geom_col(data = rt_counting_coef_sum_long,
           aes(y=mu_absregcoef),
           #method = "lm",se=F,na.rm = T,formula='y ~ x',
           position=position_dodge(width=0.9),
           fill=NA)+
  geom_point(data = rt_counting_coef_sum_long, 
           aes(y=mu_absregcoef),
           position=position_dodge(width=0.9)
           )+
  geom_errorbar(data = rt_counting_coef_sum_long, 
           aes(ymin=mu_absregcoef-se_absregcoef,
               ymax=mu_absregcoef+se_absregcoef),
           position=position_dodge(width=0.9),
           width=0.4)+
  labs(y="abs regression coefficient of counting")+
  theme(legend.position = "top",legend.direction = "horizontal",
        aspect.ratio = 1)


```





```{r}
scanning_beh = meanscanperf_with_prob%>%
  dplyr::select(-c(starts_with("UND"),starts_with("BND"),starts_with("pnorm"),starts_with("binorm"),starts_with("uniform")))

write_csv(scanning_beh,
          file.path(data_dir,"scanner_stim_LLR.csv"))


# rt_counting_coef_sub_long%>%
#   filter(isgeneralizer=="generalizer")%>%
#   aggregate_data(groupbyvars=c( "countaxis"),
#                  yvars=c("absregcoef"),
#                  stats=c("mu","se"))%>%
#   mutate(criteria = se_absregcoef)
# 
# #ggplot(training_axis_mapping,aes(x=tamapping_str,color=isgeneralizer))+geom_bar(position=position_dodge(),fill=NA)


scanning_aveperf = scanning_beh%>%
  aggregate_data(groupbyvars = c("cohort","subid","stage"),
                 yvars = "LLR_trial",
                 stats="mu")%>%
  change_cols_name("mu_LLR_trial","LLR")%>%
  pivot_wider(id_cols=c("cohort","subid"),names_from = "stage",names_prefix="LLR_",values_from ="LLR")
scanning_aveperf = left_join(training_axis_mapping,scanning_aveperf,
                             by=c("cohort","subid"))
write_csv(scanning_aveperf,
          file.path(data_dir,"scanner_average_LLR_wmapping.csv"))

```

```{r}
rt_countingformula = "resp_rt_ms~expt_trial+LR_trial+x_order+y_order+moveddist+(1|run:subid)+(-1+x_order|subid)+(-1+y_order|subid)" # didnt add random slope bc lead to singular fit
rt_fitG = lmer(data = filter(data_with_prob,stage=="test"&expt_session==3&isgeneralizer=="generalizer"),rt_countingformula)
rt_fitnG = lmer(data = filter(data_with_prob,stage=="test"&expt_session==3&isgeneralizer=="non-generalizer"),rt_countingformula)

rt_countingformula = "resp_rt_ms~isgeneralizer+x_order+y_order+expt_trial+LR_trial+moveddist+(1|run:subid)+(-1+x_order|subid)+(-1+y_order|subid)" # didnt add random slope bc lead to singular fit
rt_fitall = lmer(data = filter(data_with_prob,stage=="test"&expt_session==3),rt_countingformula)

hasConverged(rt_fitG)
hasConverged(rt_fitnG)
hasConverged(rt_fitall)
export_summs(rt_fitnG,rt_fitnG,model.names=c("Generalizers","nonGeneralizers"))

rtcountxy_coef_df1 =  data.frame(ranef(rt_fitG)$subid)
rtcountxy_coef_df1["subid"] = row.names(rtcountxy_coef_df1)
rtcountxy_coef_df2 =  data.frame(ranef(rt_fitnG)$subid)
rtcountxy_coef_df2["subid"] = row.names(rtcountxy_coef_df2)
rtcountxy_coef_df = rbind(rtcountxy_coef_df1,rtcountxy_coef_df2)

rtcountxy_coef_df =  data.frame(ranef(rt_fitall)$subid)
rtcountxy_coef_df["subid"] = row.names(rtcountxy_coef_df)

rtcountxy_coef_df = rtcountxy_coef_df%>%
  mutate(isgeneralizer=if_else(subid%in%generalizerids,"generalizer","non-generalizer"),
         cohort = if_else(str_starts(subid,"sub0"),"first cohort","second cohort"))

ggplot(rtcountxy_coef_df,aes(x=x_order,y=y_order,color=cohort))+
  facet_grid(cols=vars(isgeneralizer))+
  geom_point()+
  geom_vline(xintercept=0)+
  geom_hline(yintercept=0)

ggplot(rtcountxy_coef_df,aes(x=isgeneralizer,y=abs(x_order),color=cohort))+
  geom_point()


training_axis_mapping = rtcountxy_coef_df%>%
  change_cols_name(c("x_order","y_order"),c("countx_coef","county_coef"))%>%
  mutate(tamapping = case_when(
    sign(countx_coef)==sign(county_coef)~1, #(countx_p<0.05)&(county_p<0.05) 
    sign(countx_coef)!=sign(county_coef)~-1, # abs(countx_coef)>11.57369&abs(county_coef)>10.10267&
    .default = 0)
    )%>%
  mutate(tamapping_str = factor(tamapping,levels=c(1,-1,0),labels=c("topleft","topright","orthogonal")),
       ave_abs_count_coef = (abs(countx_coef)+abs(countx_coef))/2)%>%
  dplyr::select(c("cohort","islearner","isgeneralizer","subid","tamapping","tamapping_str",
                  "countx_coef","county_coef","ave_abs_count_coef","countx_p","county_p"))
ggplot(training_axis_mapping,aes(x=tamapping_str,color=isgeneralizer))+geom_bar(position=position_dodge(),fill=NA)

scanning_aveperf = scanning_beh%>%
  aggregate_data(groupbyvars = c("cohort","subid","stage"),
                 yvars = "LLR_trial",
                 stats="mu")%>%
  change_cols_name("mu_LLR_trial","LLR")%>%
  pivot_wider(id_cols=c("cohort","subid"),names_from = "stage",names_prefix="LLR_",values_from ="LLR")
scanning_aveperf = left_join(training_axis_mapping,scanning_aveperf,
                             by=c("cohort","subid"))
write_csv(scanning_aveperf,
          file.path(data_dir,"scanner_average_LLR_wmapping.csv"))

```


```{r}
rt_afterdist_resid_sub = rt_afterdist_resid_df%>%
  mutate(cycle = case_when(stage=="train"&expt_session==1~ceil(blocknumber_withinsess/2),
                           stage=="test"&expt_session==1~blocknumber_withinsess,
                           expt_session==2~blocknumber_withinsess+6,
                           expt_session==3~blocknumber_withinsess+6+3))%>%
  filter(cycle>=6)%>%
  #mutate(x_order=factor(x_order),
         #y_order=factor(y_order),
         #counting=factor(counting)
  #       )%>%
  aggregate_data(groupbyvars = c("cohort","islearner","isgeneralizer","subid",
                                 "session_str",
                                 "stage","counting"),
                 yvars = c("rt_resid","rtint_resid","logrt_resid","logrtint_resid"),
                 stats = c("mu","n"))%>%
  change_cols_name(c("mu_rt_resid","mu_rtint_resid","mu_logrt_resid","mu_logrtint_resid"),
                   c("rt_resid","rtint_resid","logrt_resid","logrtint_resid"))%>%
  filter(session_str == "scanning"&stage=="test")

rt_afterdist_resid_sum = rt_afterdist_resid_sub%>%
  aggregate_data(groupbyvars = c("cohort","isgeneralizer",
                                 "session_str",
                                 "stage","counting"),
                 yvars = c("rt_resid","rtint_resid","logrt_resid","logrtint_resid"),
                 stats = c("mu","se"))

ggplot(data=filter(rt_afterdist_resid_sub),
       aes(x=counting,color=cohort))+
  facet_nested(cols=vars(isgeneralizer),
               rows=vars(stage),
               scale="free_x")+
  # geom_smooth(aes(y=rt_resid,group=subid),
  #            alpha=0.01,linewidth=0.1,
  #            method = "lm",se=F,na.rm = T,formula='y ~ x',
  #             )+
  geom_point(aes(y=rt_resid),
             alpha=0.2,
             #position=position_jitterdodge(jitter.width=0.2,dodge.width = 0.9)
             position=position_dodge(width=0.6)
           )+
  geom_line(data = rt_afterdist_resid_sum,
           aes(y=mu_rt_resid),
           #method = "lm",se=F,na.rm = T,formula='y ~ x',
           position=position_dodge(width=0.6)
           )+
  geom_point(data = rt_afterdist_resid_sum, 
           aes(y=mu_rt_resid),
           position=position_dodge(width=0.6)
           )+
  geom_errorbar(data = rt_afterdist_resid_sum, 
           aes(ymin=mu_rt_resid-se_rt_resid,
               ymax=mu_rt_resid+se_rt_resid),
           position=position_dodge(width=0.6),
           width=0.4)+
  theme(legend.position = "top",legend.direction = "horizontal",
        aspect.ratio = 2)
  

```





