---
title: "3_clusterTask"
output: html_document
date: "2024-03-20"
---

```{r setup, include=FALSE}

rm(list = ls())
knitr::opts_chunk$set(error = FALSE,echo=FALSE, message=FALSE, warning=FALSE,fig.height = 9,fig.width = 16)

rm(list = ls())
project_dir = rstudioapi::getActiveProject();
src_dir = file.path(project_dir, "src/R", fsep="/")
llr_dir = file.path(project_dir, "src/LLR", fsep="/")

data_dir = file.path(project_dir, "data","Exp2_pilots","3_M2_v2", fsep="/")
result_dir = file.path(project_dir, "results","Exp2_pilots","3_M2_v2", fsep="/")

source(file.path(src_dir,"envSetup.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"funcDef.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"setPlotDefault.R",fsep="/"), local = knitr::knit_global())
#load(file.path(data_dir,"allexpdata_compo_lapse-0_01.RData"))
load(file.path(data_dir,"allexpdata_reclassify.RData"))
```

# Cluster task data
## Per Participant{.tabset}
```{r,fig.height=5,fig.width=10}
remove_sub = c("RcwaTugr8Fiz")
debrief_cluster_data = debrief_cluster_data%>%
  filter(!(subid %in% remove_sub))
generalizer_mat = list()
nongeneralizer_mat = list()
for (pid in unique(debrief_cluster_data$subid)){
  
  curr_data = filter(debrief_cluster_data,subid==pid)%>%
    dplyr::select(-c(ends_with("sx"),ends_with("sy"),"init_x","init_y","X.x","X.y"))
  curr_data = arrange(curr_data,symID)%>%
    mutate(symbol_axset = symbol_axis)
  sym_info = curr_data[,c("symID","symattr","symbol_axset","symbol_axisloc")]
  sym_info = arrange(sym_info,symbol_axset)
  sym_info_1 = change_cols_name(sym_info,oldnames = colnames(sym_info),newnames = paste0(colnames(sym_info),"_1"))
  sym_info_2 = change_cols_name(sym_info,oldnames = colnames(sym_info),newnames = paste0(colnames(sym_info),"_2"))

  sym_loc_mat = as.matrix(curr_data[,c("final_x","final_y")])
  dist_mat = pdist(sym_loc_mat)
  diag(dist_mat)=NaN
  
  if (pid %in% compositional_ids){
    if (!grepl("j5",pid)){
    generalizer_mat = append(generalizer_mat,list(dist_mat))
    }
  } else{
    nongeneralizer_mat = append(nongeneralizer_mat,list(dist_mat))
  }
  
  # dist_df = data.frame(reshape::melt.array(dist_mat))
  # colnames(dist_df) = c("symID_1","symID_2","distance")
  # dist_df = dist_df%>%
  #   mutate(symID_1=symID_1-1,
  #          symID_2=symID_2-1,
  #          )
  # dist_df = left_join(left_join(dist_df,sym_info_1,by="symID_1"),sym_info_2,by="symID_2")
  # 
  # plot_name = paste(pid,"\n",unique(curr_data$islearner),unique(curr_data$iscompositional))
  # (p2 = ggplot(data=dist_df,aes(x=symID_1,y=symID_2))+
  #     geom_tile(aes(fill=distance))+
  #     scale_x_continuous(breaks=unique(dist_df$symID_1),
  #                        labels=unique(dist_df$symattr_1))+
  #     scale_y_continuous(breaks=unique(dist_df$symID_2),
  #                        labels=unique(dist_df$symattr_2),
  #                        trans="reverse")+
  #     scale_fill_distiller(aesthetics = c("fill"),palette = "YlOrRd",na.value = "white")+
  #     labs(subtitle = "RDM from Arrangements",
  #          x="symbol",y="symbol",
  #          )+
  #     theme(legend.position = "top",
  #           aspect.ratio = 1,
  #           axis.line = element_blank(),
  #           legend.key.width = unit(dev.size()[1] / 10, "inches"))
  #   )
  # (p1=ggplot(data=curr_data,aes(x=final_x,y=final_y))+
  #     geom_text(aes(label=paste(paste0(symbol_axis,symbol_axset),symbol_axisloc,sep="_"),
  #                   color=symbol_axis,fontface="bold"))+
  #     labs(x="x",y="y",subtitle="Arrangement")+
  #     theme(legend.position = "top",legend.direction = "horizontal")
  #     )
  # p3 = ggplot()+
  #   geom_textbox(aes(x=0,y=0),
  #                width = unit(0.5, "npc"),
  #                label=paste0("debrief: ", unique(curr_data$clusterRationale)),
  #                size=4)+
  #   theme(axis.line = element_blank(),
  #         axis.text = element_blank(),
  #         axis.ticks = element_blank(),
  #         axis.title = element_blank())
  #     
  # p=grid.arrange(p1,p2,p3,nrow=1,widths=c(1,1,0.5),
  #                top=grid::textGrob(plot_name,
  #                             gp = grid::gpar(fontface = "bold", fontsize = 20)))
  # ggsave(file.path(result_dir,'individualmaps',"participant_clustertask",paste0(pid,'.png')),plot = p,width = 16,height = 9)  
}
```


##group average
```{r,fig.height=6,fig.width=12}

mean_rdm_g = Reduce("+", generalizer_mat) / length(generalizer_mat)
mean_rdm_ng = Reduce("+", nongeneralizer_mat) / length(nongeneralizer_mat)

dist_df_g = data.frame(reshape::melt.array(mean_rdm_g))
colnames(dist_df_g) = c("symID_1","symID_2","distance")
dist_df_g = dist_df_g%>%
  mutate(symID_1=symID_1-1,
         symID_2=symID_2-1,
         group = "Compositional"
         )
dist_df_ng = data.frame(reshape::melt.array(mean_rdm_ng))
colnames(dist_df_ng) = c("symID_1","symID_2","distance")
dist_df_ng = dist_df_ng%>%
  mutate(symID_1=symID_1-1,
         symID_2=symID_2-1,
         group = "nonCompositional"
         )
sym_info
dist_df = rbind(dist_df_g,dist_df_ng)
(p = ggplot(data=dist_df,aes(x=symID_1,y=symID_2))+
      facet_grid2(cols=vars(group),scales="free",axes="all")+
      geom_tile(aes(fill=distance))+
      scale_x_continuous(breaks=unique(dist_df$symID_1),
                         labels=unique(sym_info_2$symattr_1))+
      scale_y_continuous(breaks=unique(dist_df$symID_2),
                         labels=unique(sym_info_2$symattr_2),
                         trans="reverse")+
      scale_fill_distiller(aesthetics = c("fill"),palette = "YlOrRd",na.value = "white")+
      labs(x="symbol",y="symbol")+
      theme(legend.position = "top",
            aspect.ratio = 1,
            axis.line = element_blank()
            )
    )
```
