analysis = struct("sc_betweens_stimuli",{{'between_stimuli'}},...
                  "sc_alls_stimuli", {{'stimuli'}},...
                  "sc_withins_feature2d", {{'within_feature2d'}},...
                  "sc_betweens_feature2d", {{'between_feature2d'}},...
                  "sc_alls_feature2d", {{'feature2d'}},...
                  "betweens_loc2d", {{"between_loc2d"}},...
                  "withins_loc2d", {{"within_loc2d"}},...
                  "alls_loc2d", {{"loc2d"}},...
                  "betweens_loc1d", {{"between_loc1dx","between_loc1dy"}},...
                  "withins_loc1d", {{"within_loc1dx","within_loc1dy"}},...
                  "alls_loc1d", {{"loc1dx","loc1dy"}}...
                );
searchlight_par_dir = 'D:\OneDrive - Nexus365\Project\pirate_fmri\Analysis\data\fmri\searchlightrsa\noselection\fourruns';

analysis_names = fieldnames(analysis);
n_analysis = numel(analysis_names);
%% 
for k = 2:n_analysis
    searchlight_dir = fullfile(searchlight_par_dir,analysis_names{k});
    secondlevel_dir = fullfile(searchlight_dir,'second');
    participants = get_pirate_defaults(false,'participants');
    
    regressornames = analysis.(analysis_names{k});
    for j = 1:numel(regressornames)
        reg_name = regressornames{j};
        beta_img = sprintf('beta_%04d.nii',j-1);
        scans = cellfun(@(x) fullfile(searchlight_dir,'first',x,beta_img),participants.validids,'uni',0);
        specify_estimate_grouplevel(char(fullfile(secondlevel_dir,reg_name)),...
                                    {scans},...
                                    cellstr(reg_name));
        specify_estimate_contrast(char(fullfile(secondlevel_dir,reg_name)),...
                                  cellstr(reg_name),...
                                  {[1]});
        report_results(char(fullfile(secondlevel_dir,reg_name)))
    end
    pause
end