---
title: "stability"
author: "zilu"
date: "2024-12-05"
output: html_document
---


```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(error = FALSE,echo=FALSE, message=FALSE, warning=FALSE)

rm(list = ls())
project_dir = rstudioapi::getActiveProject();
src_dir = file.path(project_dir, "src/R", fsep="/")
llr_dir = file.path(project_dir, "src/LLR", fsep="/")

data_dir = file.path(project_dir, "data","Exp1_fmri", fsep="/")
result_dir = file.path(project_dir, "results","Exp1_fmri", fsep="/")


source(file.path(src_dir,"envSetup.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"funcDef.R",fsep="/"), local = knitr::knit_global())
source(file.path(src_dir,"setPlotDefault.R",fsep="/"), local = knitr::knit_global())
```

```{r}
data_with_prob = loadRData(file.path(data_dir,"filtereddata_withprob_compo_lapse-0_01.RData"))
meanscanperf_with_prob = loadRData(file.path(data_dir,"filteredmeanscannerdata_withprob_compo_lapse-0_01.RData"))

```

## response stability
quantify response stability with correlation approach - for each two blocks how correlated are the response (and error)?

#### response
```{r}
stability_df = data.frame()
subid_list = unique(data_with_prob$subid)
for (pid in subid_list){
  #pid = subid_list[1]
  current_data = data_with_prob%>%filter(subid==pid)
  unique_train_blocknum = unique(filter(current_data,stage=="train")$expt_block)
  unique_test_blocknum = unique(filter(current_data,stage=="test")$expt_block)
  nb_train = length(unique_train_blocknum)
  nb_test = length(unique_test_blocknum)
  
  stability_trainx = c()
  stability_trainy = c()
  stability_trainxy = c()
  for (i in seq(2,nb_train,1)){
    j=unique_train_blocknum[i-1]
    k=unique_train_blocknum[i]
    prev_x = arrange(filter(current_data,stage=="train",expt_block==j),stim_id)$resp_x
    prev_y = arrange(filter(current_data,stage=="train",expt_block==j),stim_id)$resp_y
    curr_x = arrange(filter(current_data,stage=="train",expt_block==k),stim_id)$resp_x
    curr_y = arrange(filter(current_data,stage=="train",expt_block==k),stim_id)$resp_y
    
    stability_trainx = append(stability_trainx,cor(prev_x,curr_x))
    stability_trainy = append(stability_trainy,cor(prev_y,curr_y))
    stability_trainxy = append(stability_trainxy,
                             cor(c(prev_x,prev_y), c(curr_x,curr_y)))
  }
  train_stabdf = data.frame(stability_x = stability_trainx,
             stability_y=stability_trainy,
             stability_xy = stability_trainxy,
             expt_block=unique_train_blocknum[2:nb_train])%>%
    mutate(stage="train")
  
  stability_testx = c()
  stability_testy = c()
  stability_testxy = c()
  for (i in seq(2,nb_test,1)){
    j=unique_test_blocknum[i-1]
    k=unique_test_blocknum[i]
    prev_x = arrange(filter(current_data,stage=="test",expt_block==j),stim_id)$resp_x
    prev_y = arrange(filter(current_data,stage=="test",expt_block==j),stim_id)$resp_y
    curr_x = arrange(filter(current_data,stage=="test",expt_block==k),stim_id)$resp_x
    curr_y = arrange(filter(current_data,stage=="test",expt_block==k),stim_id)$resp_y
    
    stability_testx = append(stability_testx,
                             cor(prev_x, curr_x))
    stability_testy = append(stability_testy,
                             cor(prev_y, curr_y))
    stability_testxy = append(stability_testxy,
                             cor(c(prev_x,prev_y), c(curr_x,curr_y)))
  }
  test_stabdf = data.frame(stability_x = stability_testx,
             stability_y=stability_testy,
             stability_xy = stability_testxy,
             expt_block=unique_test_blocknum[2:nb_test])%>%
    mutate(stage="test")
  
  sdf = rbind(train_stabdf,test_stabdf)%>%mutate(
    subid=pid,
    cohort=unique(current_data$cohort),
    islearner=unique(current_data$islearner),
    isgeneralizer=unique(current_data$isgeneralizer))
  
  substab_df = left_join(filter(re_Assign_block,subid==pid,expt_block!=unique_train_blocknum[1],expt_block!=unique_test_blocknum[1]),
                         sdf,
                         by = c("subid", "stage", "expt_block"))
  stability_df = rbind(stability_df,substab_df)
}

```


```{r}
stability_df = stability_df %>%
  mutate(session_str=factor(expt_session, levels = c(1,2,3),labels=c("pretraining","refresher","scanning")))%>%
  mutate(cycle = case_when(stage=="train"&expt_session==1~ceil(blocknumber_withinsess/2),
                           stage=="test"&expt_session==1~blocknumber_withinsess,
                           expt_session==2~blocknumber_withinsess+6,
                           expt_session==3~blocknumber_withinsess+6+3))
  
stability_df_long =stability_df%>%
  filter(cycle>=6)%>%
  pivot_longer(cols=c("stability_x","stability_y","stability_xy"),names_to = "axis",values_to = "stability")%>%
  filter(isgeneralizer=="generalizer"&axis=="stability_xy")%>%
  mutate(stage=factor(stage,levels=c("train","test")))

stability_df_long_sum = stability_df_long%>%
  aggregate_data(yvars = c("stability"),
                 groupbyvars = c("cohort","islearner","isgeneralizer","stage",
                                 "expt_session","cycle","axis"),
                 stats = c("mu","se","n"),
                 additionalvars = c("session_str","expt_block"))
(p = stability_df_long%>%
  ggplot(aes(x=cycle,y=stability,color=cohort))+
  geom_point(alpha = 0.2,size = 2,stroke = 0,position=position_dodge(width=0.5))+
  geom_line(data = stability_df_long_sum,
            aes(x=cycle,y=mu_stability),position=position_dodge(width=0.5))+
  geom_errorbar(data = stability_df_long_sum,
                aes(x=cycle,
                    y = mu_stability,
                    ymin = mu_stability - se_stability,
                    ymax = mu_stability + se_stability),
                width=0.4,position=position_dodge(width=0.5))+
  facet_nested(cols = vars(session_str),
               rows = vars(stage),drop=T,
               independent="x",
               scales = "free_x",space="free_x",axes="all",remove_labels="y")+
  scale_x_continuous(breaks=seq(6,14))+
  labs(x="block number",y="correlation with previous block",color = "cohort",
       title = "response stability of generalizers")+
  theme(aspect.ratio = 1.5,legend.position = "top"))

ggsave(file.path(result_dir,paste0('stability','.png')),plot = p,device = 'png',width = 8,height = 8)
```

#### response error
```{r}
err_stability_df = data.frame()
subid_list = unique(data_with_prob$subid)
for (pid in subid_list){
  current_data = data_with_prob%>%filter(subid==pid)
  unique_train_blocknum = unique(filter(current_data,stage=="train")$expt_block)
  unique_test_blocknum = unique(filter(current_data,stage=="test")$expt_block)
  nb_train = length(unique_train_blocknum)
  nb_test = length(unique_test_blocknum)
  
  stability_trainx = c()
  stability_trainy = c()
  stability_trainxy = c()
  for (i in seq(2,nb_train,1)){
    j=unique_train_blocknum[i-1]
    k=unique_train_blocknum[i]
    prev_x = arrange(filter(current_data,stage=="train",expt_block==j),stim_id)$error_x
    prev_y = arrange(filter(current_data,stage=="train",expt_block==j),stim_id)$error_y
    curr_x = arrange(filter(current_data,stage=="train",expt_block==k),stim_id)$error_x
    curr_y = arrange(filter(current_data,stage=="train",expt_block==k),stim_id)$error_y
    
    stability_trainx = append(stability_trainx,cor(prev_x,curr_x))
    stability_trainy = append(stability_trainy,cor(prev_y,curr_y))
    stability_trainxy = append(stability_trainxy,
                             cor(c(prev_x,prev_y), c(curr_x,curr_y)))
  }
  train_stabdf = data.frame(stability_x = stability_trainx,
             stability_y=stability_trainy,
             stability_xy = stability_trainxy,
             expt_block=unique_train_blocknum[2:nb_train])%>%
    mutate(stage="train")
  
  stability_testx = c()
  stability_testy = c()
  stability_testxy = c()
  for (i in seq(2,nb_test,1)){
    j=unique_test_blocknum[i-1]
    k=unique_test_blocknum[i]
    prev_x = arrange(filter(current_data,stage=="test",expt_block==j),stim_id)$error_x
    prev_y = arrange(filter(current_data,stage=="test",expt_block==j),stim_id)$error_y
    curr_x = arrange(filter(current_data,stage=="test",expt_block==k),stim_id)$error_x
    curr_y = arrange(filter(current_data,stage=="test",expt_block==k),stim_id)$error_y
    
    stability_testx = append(stability_testx,
                             cor(prev_x, curr_x))
    stability_testy = append(stability_testy,
                             cor(prev_y, curr_y))
    stability_testxy = append(stability_testxy,
                             cor(c(prev_x,prev_y), c(curr_x,curr_y)))
  }
  test_stabdf = data.frame(stability_x = stability_testx,
             stability_y=stability_testy,
             stability_xy = stability_testxy,
             expt_block=unique_test_blocknum[2:nb_test])%>%
    mutate(stage="test")
  
  sdf = rbind(train_stabdf,test_stabdf)%>%mutate(
    subid=pid,
    cohort=unique(current_data$cohort),
    islearner=unique(current_data$islearner),
    isgeneralizer=unique(current_data$isgeneralizer))
  
  substab_df = left_join(filter(re_Assign_block,subid==pid,expt_block!=unique_train_blocknum[1],expt_block!=unique_test_blocknum[1]),
                         sdf,
                         by = c("subid", "stage", "expt_block"))
  err_stability_df = rbind(err_stability_df,substab_df)
}

```


```{r}
err_stability_df = err_stability_df %>%
  mutate(session_str=factor(expt_session, levels = c(1,2,3),labels=c("pretraining","refresher","scanning")))%>%
  mutate(cycle = case_when(stage=="train"&expt_session==1~ceil(blocknumber_withinsess/2),
                           stage=="test"&expt_session==1~blocknumber_withinsess,
                           expt_session==2~blocknumber_withinsess+6,
                           expt_session==3~blocknumber_withinsess+6+3))
  
errstability_df_long =err_stability_df%>%
  filter(cycle>=6)%>%
  pivot_longer(cols=c("stability_x","stability_y","stability_xy"),names_to = "axis",values_to = "stability")%>%
  filter(isgeneralizer==1&axis!="stability_xy")

errstability_df_long_sum = errstability_df_long%>%
  aggregate_data(yvars = c("stability"),
                 groupbyvars = c("cohort","islearner","isgeneralizer","stage",
                                 "expt_session","cycle","axis"),
                 stats = c("mu","se","n"),
                 additionalvars = c("session_str","expt_block"))
(p = errstability_df_long%>%
  ggplot(aes(x=cycle,y=stability,color=cohort))+
  geom_point(alpha = 0.2,size = 2,stroke = 0,position=position_dodge(width=0.8))+
  geom_line(data = errstability_df_long_sum,
            aes(x=cycle,y=mu_stability),position=position_dodge(width=0.8))+
  geom_errorbar(data = errstability_df_long_sum,
                aes(x=cycle,
                    y = mu_stability,
                    ymin = mu_stability - se_stability,
                    ymax = mu_stability + se_stability),
                width=0.4,position=position_dodge(width=0.8))+
  geom_col(data = errstability_df_long_sum,
           aes(x=cycle,y = mu_stability),fill=NA,
             position=position_dodge(width=0.8),width=0.6)+
  facet_nested(cols = vars(session_str,stage),
               rows = vars(axis),
               scales = "free_x",space = "free_x")+
  scale_x_continuous(breaks = seq(6,13,1))+
  labs(x="block number",y="mean error stability",color = "cohort",
       title = "performance of learners and generalizers")+
  theme(aspect.ratio = 6,legend.position = "top"))

ggsave(file.path(result_dir,paste0('errstability','.png')),plot = p,device = 'png',width = 10,height = 9)
```
